packages:
  - apps/*
  - packages/**/*
  - tooling/*

catalog:
  '@codemirror/autocomplete': 6.19.1
  '@codemirror/commands': 6.10.0
  '@codemirror/lang-html': 6.4.11
  '@codemirror/lang-json': 6.0.2
  '@codemirror/lang-markdown': 6.5.0
  '@codemirror/language': 6.11.3
  '@codemirror/lint': 6.9.2
  '@codemirror/search': 6.5.11
  '@codemirror/state': 6.5.2
  '@codemirror/theme-one-dark': 6.1.3
  '@codemirror/view': 6.38.6
  '@date-fns/tz': 1.4.1
  '@dnd-kit/core': ^6.3.1
  '@dnd-kit/modifiers': ^9.0.0
  '@dnd-kit/sortable': ^10.0.0
  '@dnd-kit/utilities': ^3.2.2
  '@eslint/js': ^9.39.1
  '@floating-ui/dom': 1.7.4
  '@hono/node-server': ^1.19.6
  '@hono/vite-build': ^1.6.2
  '@hono/vite-dev-server': ^0.20.0
  '@hono/zod-validator': 0.7.4
  '@hookform/resolvers': 5.2.2
  '@kit/api': workspace:*
  '@kit/auth': workspace:*
  '@kit/database-editor': 0.1.0
  '@kit/eslint-config': workspace:*
  '@kit/prettier-config': workspace:*
  '@kit/supabase': workspace:*
  '@kit/tailwind-config': 0.1.0
  '@kit/typescript-config': workspace:*
  '@kit/ui': workspace:*
  '@lexical/code': 0.38.2
  '@lexical/code-shiki': 0.38.2
  '@lexical/history': 0.38.2
  '@lexical/html': 0.38.2
  '@lexical/link': 0.38.2
  '@lexical/list': 0.38.2
  '@lexical/markdown': 0.38.2
  '@lexical/react': 0.38.2
  '@lexical/rich-text': 0.38.2
  '@lexical/selection': 0.38.2
  '@lexical/table': 0.38.2
  '@lexical/utils': 0.38.2
  '@manypkg/cli': ^0.25.1
  '@marsidev/react-turnstile': 1.3.1
  '@playwright/test': ^1.56.1
  '@radix-ui/react-icons': ^1.3.2
  '@radix-ui/react-portal': 1.1.10
  '@supabase/ssr': ^0.7.0
  '@supabase/supabase-js': ^2.79.0
  '@tailwindcss/vite': ^4.1.16
  '@tanstack/react-query': 5.90.7
  '@tanstack/react-table': ^8.21.3
  '@trivago/prettier-plugin-sort-imports': ^6.0.0
  '@turbo/gen': ^2.6.0
  '@types/chalk': ^2.2.4
  '@types/eslint': 9.6.1
  '@types/node': ^24.10.0
  '@types/react': 19.2.2
  '@types/react-color': ^3.0.13
  '@types/react-dom': 19.2.2
  '@types/react-grid-layout': ^1.3.5
  '@typescript-eslint/eslint-plugin': ^7.5.0
  '@typescript-eslint/parser': ^7.5.0
  '@vercel/style-guide': ^5.2.0
  '@vitejs/plugin-react': ^5.1.0
  '@vitest/coverage-v8': ^4.0.7
  autoprefixer: ^10.4.20
  chalk: ^5.6.2
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  cmdk: 1.1.1
  codemirror: 6.0.2
  commander: ^14.0.2
  date-fns: ^4.1.0
  dotenv: 17.2.3
  dotenv-cli: ^11.0.0
  drizzle-kit: ^0.31.6
  drizzle-orm: ^0.44.7
  eslint: ^9.39.1
  eslint-config-prettier: ^9.1.0
  eslint-config-turbo: ^2.6.0
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.24
  globals: ^15.11.0
  hono: ^4.10.4
  i18next-browser-languagedetector: ^8.2.0
  i18next-resources-to-backend: ^1.2.1
  input-otp: 1.4.2
  jwt-decode: ^4.0.0
  lexical: 0.38.2
  lucide-react: ^0.552.0
  next-themes: ^0.4.6
  pino: ^10.1.0
  pino-pretty: ^13.0.0
  postgres: ^3.4.7
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.7.1
  radix-ui: ^1.4.3
  react: 19.2.0
  react-color: 2.19.3
  react-day-picker: ^9.11.1
  react-dom: 19.2.0
  react-dropzone: 14.3.8
  react-fast-compare: ^3.2.2
  react-grid-layout: ^1.4.4
  react-hook-form: ^7.66.0
  react-i18next: ^16.2.4
  react-markdown: 10.1.0
  react-router: ^7.9.5
  react-top-loading-bar: 3.0.2
  recharts: 2.15.3
  remark-gfm: 4.0.1
  rxjs: ^7.8.2
  shiki: 3.14.0
  sonner: ^2.0.7
  supabase: 2.54.11
  tailwind-merge: ^3.3.1
  tailwindcss: 4.1.16
  tailwindcss-animate: ^1.0.7
  tsup: 8.5.0
  tsx: 4.20.6
  turbo: ^2.6.0
  tw-animate-css: 1.4.0
  typescript: ^5.9.3
  typescript-eslint: 8.46.3
  vite: ^7.2.1
  vitest: ^4.0.7
  zod: ^4.1.12

onlyBuiltDependencies:
  - '@snaplet/seed'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - '@snaplet/seed'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - supabase
